/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_lp_primeiro;

import DAO.EmprestimosDAO;
import DAO.LivroDAO;
import DAO.UsuarioDAO;
import MODELO.EMPRESTIMOS;
import MODELO.CADASTRO_USUARIO;
import MODELO.LIVRO;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jsmai
 */
public class PAINEL_INICIAL extends javax.swing.JFrame {

    /**
     * Creates new form PAINEL_INICIAL
     */
    public PAINEL_INICIAL() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

    }
    UsuarioDAO User_dao = new UsuarioDAO();
    LivroDAO book_dao = new LivroDAO();
    EmprestimosDAO EM_dao = new EmprestimosDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cadastrar_usuario = new javax.swing.JButton();
        LISTAR_USUARIO = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        LISTAR_LIVRO = new javax.swing.JButton();
        REALIZAR_EMPRESTIMO = new javax.swing.JButton();
        REGISTRAR_DEVOLUCAO = new javax.swing.JButton();
        LISTAR_EMPRESTIMO = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastrar_usuario.setBackground(new java.awt.Color(204, 204, 204));
        cadastrar_usuario.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        cadastrar_usuario.setBorder(null);
        cadastrar_usuario.setContentAreaFilled(false);
        cadastrar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 230, 50));

        LISTAR_USUARIO.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LISTAR_USUARIO.setContentAreaFilled(false);
        LISTAR_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTAR_USUARIOActionPerformed(evt);
            }
        });
        jPanel1.add(LISTAR_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 130, 210, 50));

        jButton3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 220, 50));

        LISTAR_LIVRO.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LISTAR_LIVRO.setContentAreaFilled(false);
        LISTAR_LIVRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTAR_LIVROActionPerformed(evt);
            }
        });
        jPanel1.add(LISTAR_LIVRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 204, 220, 50));

        REALIZAR_EMPRESTIMO.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        REALIZAR_EMPRESTIMO.setContentAreaFilled(false);
        REALIZAR_EMPRESTIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REALIZAR_EMPRESTIMOActionPerformed(evt);
            }
        });
        jPanel1.add(REALIZAR_EMPRESTIMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 274, 220, 50));

        REGISTRAR_DEVOLUCAO.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        REGISTRAR_DEVOLUCAO.setContentAreaFilled(false);
        REGISTRAR_DEVOLUCAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRAR_DEVOLUCAOActionPerformed(evt);
            }
        });
        jPanel1.add(REGISTRAR_DEVOLUCAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 274, 220, 50));

        LISTAR_EMPRESTIMO.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LISTAR_EMPRESTIMO.setContentAreaFilled(false);
        LISTAR_EMPRESTIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTAR_EMPRESTIMOActionPerformed(evt);
            }
        });
        jPanel1.add(LISTAR_EMPRESTIMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 354, 220, 40));

        jButton8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, 50));

        jButton9.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 454, 160, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca_HP.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 513));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_usuarioActionPerformed
        String nome = JOptionPane.showInputDialog("Nome do usuário:");
        String email = JOptionPane.showInputDialog("Email do usuário:");
        UsuarioDAO User_dao = new UsuarioDAO();
        if (nome != null && email != null) {
            User_dao(new CADASTRO_USUARIO(nome, email));
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
        }
    }//GEN-LAST:event_cadastrar_usuarioActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String titulo = JOptionPane.showInputDialog("Título do livro:");
        String autor = JOptionPane.showInputDialog("Autor do livro:");

        if (titulo != null && autor != null) {
            try {
                book_dao.cadastrar(new LIVRO(titulo, autor));
            } catch (SQLException ex) {
                Logger.getLogger(PAINEL_INICIAL.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LISTAR_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTAR_USUARIOActionPerformed
        StringBuilder sb = new StringBuilder();
        try {
            for (CADASTRO_USUARIO Usuario : User_dao.listar()) {
                sb.append(Usuario.toString()).append("\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PAINEL_INICIAL.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, sb.toString(), "Usuários", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_LISTAR_USUARIOActionPerformed

    private void LISTAR_LIVROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTAR_LIVROActionPerformed
        StringBuilder sb = new StringBuilder();
        try {
            for (LIVRO l : book_dao.listarTodos()) {
                sb.append(l.toString()).append("\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PAINEL_INICIAL.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, sb.toString(), "Livros", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_LISTAR_LIVROActionPerformed

    private void REALIZAR_EMPRESTIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REALIZAR_EMPRESTIMOActionPerformed
        int idUsuario = Integer.parseInt(JOptionPane.showInputDialog("ID do usuário:"));
        int idLivro = Integer.parseInt(JOptionPane.showInputDialog("ID do livro:"));

        EMPRESTIMOS emp = new EMPRESTIMOS(idUsuario, idLivro, LocalDate.now(), LocalDate.now().plusDays(7), "EM ANDAMENTO");
        EM_dao.adicionarEmprestimo(emp);
        JOptionPane.showMessageDialog(null, "Empréstimo registrado!");
    }//GEN-LAST:event_REALIZAR_EMPRESTIMOActionPerformed

    private void REGISTRAR_DEVOLUCAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRAR_DEVOLUCAOActionPerformed
        int idEmp = Integer.parseInt(JOptionPane.showInputDialog("ID do empréstimo:"));
        EM_dao.registrarDevolucao(idEmp);
        JOptionPane.showMessageDialog(null, "Devolução registrada!");
    }//GEN-LAST:event_REGISTRAR_DEVOLUCAOActionPerformed

    private void LISTAR_EMPRESTIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTAR_EMPRESTIMOActionPerformed
        StringBuilder sb = new StringBuilder();
        for (EMPRESTIMOS E : EM_dao.listarEmprestimos()) {
            sb.append(E.toString()).append("\n");
        }
        JOptionPane.showMessageDialog(null, sb.toString(), "EMPRESTIMOS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_LISTAR_EMPRESTIMOActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        StringBuilder sb = new StringBuilder();
        for (EMPRESTIMOS E : EM_dao.listarAtrasados()) {
            sb.append(E.toString()).append("\n");
        }
        JOptionPane.showMessageDialog(null, sb.toString(), "EMPRESTIMOS ATRASADOS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAINEL_INICIAL.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAINEL_INICIAL.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAINEL_INICIAL.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAINEL_INICIAL.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAINEL_INICIAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LISTAR_EMPRESTIMO;
    private javax.swing.JButton LISTAR_LIVRO;
    private javax.swing.JButton LISTAR_USUARIO;
    private javax.swing.JButton REALIZAR_EMPRESTIMO;
    private javax.swing.JButton REGISTRAR_DEVOLUCAO;
    private javax.swing.JButton cadastrar_usuario;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void User_dao(CADASTRO_USUARIO cadastro_usuario) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
