/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_lp_primeiro;

import DAO.EmprestimosDAO;
import DAO.LivroDAO;
import DAO.UsuarioDAO;
import MODELO.EMPRESTIMOS;
import MODELO.CADASTRO_USUARIO;
import MODELO.LIVRO;
import java.util.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jsmai
 */
public class PAINEL_INICIAL extends javax.swing.JFrame {

    UsuarioDAO User_dao = new UsuarioDAO();
    /**
     * Creates new form PAINEL_INICIAL
     */
    public PAINEL_INICIAL() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

    }
    LivroDAO book_dao = new LivroDAO();
    EmprestimosDAO EM_dao = new EmprestimosDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cadastrar_usuario = new javax.swing.JButton();
        LISTAR_USUARIO = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        LISTAR_LIVRO = new javax.swing.JButton();
        REALIZAR_EMPRESTIMO = new javax.swing.JButton();
        REGISTRAR_DEVOLUCAO = new javax.swing.JButton();
        LISTAR_EMPRESTIMO = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setText("BIBLIOTECA VAQUEIRO MG ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("SELECIONE 1 DAS OPÇÕES ABAIXO:");

        cadastrar_usuario.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        cadastrar_usuario.setText("1 - Cadastrar usuário");
        cadastrar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_usuarioActionPerformed(evt);
            }
        });

        LISTAR_USUARIO.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LISTAR_USUARIO.setText("2 - Listar usuários");
        LISTAR_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTAR_USUARIOActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton3.setText("3 - Cadastrar livro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        LISTAR_LIVRO.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LISTAR_LIVRO.setText("4 - Listar livros");
        LISTAR_LIVRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTAR_LIVROActionPerformed(evt);
            }
        });

        REALIZAR_EMPRESTIMO.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        REALIZAR_EMPRESTIMO.setText("5 - Realizar empréstimo");
        REALIZAR_EMPRESTIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REALIZAR_EMPRESTIMOActionPerformed(evt);
            }
        });

        REGISTRAR_DEVOLUCAO.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        REGISTRAR_DEVOLUCAO.setText("6 - Registrar devolução");
        REGISTRAR_DEVOLUCAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRAR_DEVOLUCAOActionPerformed(evt);
            }
        });

        LISTAR_EMPRESTIMO.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LISTAR_EMPRESTIMO.setText("7 - Listar empréstimos");
        LISTAR_EMPRESTIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTAR_EMPRESTIMOActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton8.setText("8 - Listar empréstimos atrasados");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton9.setText("0 - Sair");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cadastrar_usuario)
                .addGap(28, 28, 28)
                .addComponent(LISTAR_USUARIO))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(LISTAR_LIVRO, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(REALIZAR_EMPRESTIMO)
                .addGap(14, 14, 14)
                .addComponent(REGISTRAR_DEVOLUCAO))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LISTAR_EMPRESTIMO)
                .addGap(23, 23, 23)
                .addComponent(jButton8))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrar_usuario)
                    .addComponent(LISTAR_USUARIO))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(LISTAR_LIVRO))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(REALIZAR_EMPRESTIMO)
                    .addComponent(REGISTRAR_DEVOLUCAO))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LISTAR_EMPRESTIMO)
                    .addComponent(jButton8))
                .addGap(12, 12, 12)
                .addComponent(jButton9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_usuarioActionPerformed
        String nome = JOptionPane.showInputDialog("Nome do usuário:");
        String email = JOptionPane.showInputDialog("Email do usuário:");
        if (nome != null && email != null) {
            try {
                User_dao.cadastrar(new CADASTRO_USUARIO(nome, email));
                JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao inserir usuário!");
                Logger.getLogger(PAINEL_INICIAL.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cadastrar_usuarioActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String titulo = JOptionPane.showInputDialog("Título do livro:");
        String autor = JOptionPane.showInputDialog("Autor do livro:");

        if (titulo != null && autor != null) {
            try {
                book_dao.cadastrar(new LIVRO(titulo, autor));
            } catch (SQLException ex) {
                Logger.getLogger(PAINEL_INICIAL.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LISTAR_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTAR_USUARIOActionPerformed
        StringBuilder sb = new StringBuilder();
        try {
            for (CADASTRO_USUARIO Usuario : User_dao.listar()) {
                sb.append(Usuario.toString()).append("\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PAINEL_INICIAL.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, sb.toString(), "Usuários", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_LISTAR_USUARIOActionPerformed

    private void LISTAR_LIVROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTAR_LIVROActionPerformed
        StringBuilder sb = new StringBuilder();
        try {
            for (LIVRO l : book_dao.listarTodos()) {
                sb.append(l.toString()).append("\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PAINEL_INICIAL.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, sb.toString(), "Livros", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_LISTAR_LIVROActionPerformed

    private void REALIZAR_EMPRESTIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REALIZAR_EMPRESTIMOActionPerformed
        int idUsuario = Integer.parseInt(JOptionPane.showInputDialog("ID do usuário:"));
        int idLivro = Integer.parseInt(JOptionPane.showInputDialog("ID do livro:"));

        Date dataAtual = new Date();

        // 2. Usar Calendar para adicionar dias
        Calendar c = Calendar.getInstance();
        c.setTime(dataAtual); // Define a data atual no Calendar
        c.add(Calendar.DAY_OF_MONTH, 7); // Adiciona 7 dias
        Date dataFutura = c.getTime();
        System.out.println(dataFutura);
        EMPRESTIMOS emp = new EMPRESTIMOS(idUsuario, idLivro, dataAtual , dataFutura, "EM ANDAMENTO");
        EM_dao.adicionarEmprestimo(emp);
        JOptionPane.showMessageDialog(null, "Empréstimo registrado!");
    }//GEN-LAST:event_REALIZAR_EMPRESTIMOActionPerformed

    private void REGISTRAR_DEVOLUCAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRAR_DEVOLUCAOActionPerformed
        int idEmp = Integer.parseInt(JOptionPane.showInputDialog("ID do empréstimo:"));
        EM_dao.registrarDevolucao(idEmp);
        JOptionPane.showMessageDialog(null, "Devolução registrada!");
    }//GEN-LAST:event_REGISTRAR_DEVOLUCAOActionPerformed

    private void LISTAR_EMPRESTIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTAR_EMPRESTIMOActionPerformed
        StringBuilder sb = new StringBuilder();
        for (EMPRESTIMOS E : EM_dao.listarEmprestimos()) {
            sb.append(E.toString()).append("\n");
        }
        JOptionPane.showMessageDialog(null, sb.toString(), "EMPRESTIMOS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_LISTAR_EMPRESTIMOActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        StringBuilder sb = new StringBuilder();
        for (EMPRESTIMOS E : EM_dao.listarAtrasados()) {
            sb.append(E.toString()).append("\n");
        }
        JOptionPane.showMessageDialog(null, sb.toString(), "EMPRESTIMOS ATRASADOS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAINEL_INICIAL.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAINEL_INICIAL.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAINEL_INICIAL.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAINEL_INICIAL.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAINEL_INICIAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LISTAR_EMPRESTIMO;
    private javax.swing.JButton LISTAR_LIVRO;
    private javax.swing.JButton LISTAR_USUARIO;
    private javax.swing.JButton REALIZAR_EMPRESTIMO;
    private javax.swing.JButton REGISTRAR_DEVOLUCAO;
    private javax.swing.JButton cadastrar_usuario;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


}
